export const generalImages = [
  {
    id: "1",
    src: "/sharekit/general-1.png",
    title: "",
    dimension: "1.920 x 1080",
    format: "landscape",
    alt: "General image 1",
  },
  {
    id: "2",
    src: "/sharekit/general-2.png",
    title: "",
    dimension: "",
    format: "landscape",
    alt: "General image 2",
  },
    {
    id: "5",
    src: "/sharekit/general-1.png",
    title: "",
    dimension: "1.920 x 1080",
    format: "landscape",
    alt: "General image 1",
  },
  {
    id: "6",
    src: "/sharekit/general-2.png",
    title: "",
    dimension: "",
    format: "landscape",
    alt: "General image 2",
  },
  {
    id: "3",
    src: "/sharekit/general-3.png",
    title: "",
    dimension: "",
    format: "portrait",
    alt: "General image 3",
  },
  {
    id: "4",
    src: "/sharekit/general-4.png",
    title: "",
    dimension: "",
    format: "portrait",
    alt: "General image 4",
  },
] as const;